### ISSUE TITLE
Issues when installing KDEpy

### ISSUE THREAD

**Issue by devesh1508** [tommyod/KDEpy#1]
When running python setup.py or pip install KDEpy (on python 2.7), get the following error
from KDEpy import __version__

def __init__(self, kernel: str, bw: float):
                             ^
SyntaxError: invalid syntax

**Comment by tommyod** [comment]
I've been developing for Python 3.6.

I will look into whether it can be easily backported to Python 2.7.

What is your operating system @devesh1508 ?

**Comment by devesh1508** [comment]
The OS is Ubuntu 16.04. With python 3.6 (in a virtual env),
I get the following error
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
-Command "/homes/jha/KDE/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tpyimiri/KDEpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rge7raxi/install-record.txt --single-version-externally-managed --compile --install-headers /homes/jha/KDE/include/site/python3.6/KDEpy" failed with error code 1 in /tmp/pip-install-tpyimiri/KDEpy/

**Comment by tommyod** [comment]
Thank you for reporting this. This is the first time I've tried to distribute with Cython as a requirement. I've found some errors which I will fix. In the meantime, installing some dependencies *before* KDEpy works on my computer (Ubuntu 16.04 using Anaconda).

Create a fresh environment, then install dependencies *before* KDEpy.
```
$ conda create -n kde python=3.6
$ source activate kde
$ conda install numpy scipy cython
$ pip install KDEpy
```
Now everything seems to work.
```
$ python
>>> import numpy as np
>>> from KDEpy import FFTKDE
>>> x, y = FFTKDE().fit(np.random.randn(10**5)).evaluate()
>>> exit()
$ source deactivate 
```

Can you try installing `numpy scipy cython` before KDEpy?

**Comment by tommyod** [comment]
**Update:** Managed to ship a compiled `.c` file. The following now works for me.

I create an environment called `kde` with `numpy` installed, install KDEpy, test that it works, deactivate and delete the environment.

```
$ conda create -n kde python=3.6 numpy
$ conda activate kde
$ pip install KDEpy --no-cache-dir
$ python
>>> from KDEpy import FFTKDE
>>> x, y = FFTKDE().fit([1, 2, 3]).evaluate()
>>> exit()
$ conda deactivate
$ conda env remove -n kde
```

Can you give it a shot? Thanks.

**Comment by devesh1508** [comment]
Thanks for both the suggestions. One question before I try them-- Do I need anaconda? I use default python. Would it work without anaconda?

**Comment by tommyod** [comment]
In principle you should not need anaconda. However, it's a great tool because it lets you install multiple Python environments in parallel -- that's how I'm able to create a "throwaway" environment for testing this particular problem. I would recommend Anaconda.

You're free to try without too of course(let me know how it goes!). I've been working on installation issues all day. I've managed to get it working on my Ubuntu machines, and on Windows too. Still more work to do before it's perfect. I didn't anticipate it being this difficult, so thanks for the patience!

**Comment by devesh1508** [comment]
@tommyod  Sorry for a late reply. I did pip install KDEpy with python 3.6 and it works now. Thanks for all your help

**Comment by tommyod** [comment]
Great to hear! Thanks for reporting, and for the patience.
