### ISSUE TITLE
density estimation on 4D data

### ISSUE THREAD

**Issue by herrerandresc** [tommyod/KDEpy#109]
Hi! I watched your video on youtube and discovered your library.  I'm trying to estimate pdf on 4D data. I'm trying to use NaiveKDE class, with the fit and evaluate method and it returns x, y; where x is a (625,) array and y is a (625, 4) array, which I don't understand because my data is (87564, 4) array. Here I don't understand what does mean the x and the y. I want to know the pdf and get the probability of new points evaluated on the estimation of the pdf. Could you please help me with this?

Best regards,

Andrés

**Comment by tommyod** [comment]
The shape of the returned x seems wrong. Can you provide a minimal (non-)working example with some dummy data?

**Comment by herrerandresc** [comment]
I'm trying this:

data = np.random.random((87564,4))
print(data.shape)

x, y = NaiveKDE(kernel="gaussian", bw=0.1).fit(data).evaluate()

print(x.shape)
print(y.shape)

**Comment by tommyod** [comment]
The shapes seem correct to me:

```python
from KDEpy import NaiveKDE
import numpy as np
import KDEpy

print(KDEpy.__version__) # 1.1.0

data = np.random.random((1000, 4))
print(data.shape)

x, y = NaiveKDE(kernel="gaussian", bw=0.1).fit(data).evaluate()

print(x.shape) # (625, 4)
print(y.shape) # (625,)
```

Could you double-check?
