### ISSUE TITLE
Cytopy needs KDEpy version 1.0.10, but pip says it doesn't exist.

### ISSUE THREAD

**Issue by AlexanderWMacFarlaneIV** [tommyod/KDEpy#112]
pip install cytopy gives this error:
The conflict is caused by:
    cytopy 2.0.1 depends on KDEpy==1.0.10
    cytopy 2.0 depends on KDEpy==1.0.10

pip install kdepy==1.0.10 gives this error:
ERROR: Could not find a version that satisfies the requirement kdepy==1.0.10 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6, 0.6.9, 0.6.10, 0.6.11, 1.0.2, 1.0.11, 1.1.0)
ERROR: No matching distribution found for kdepy==1.0.10

Installing KDEpy 1.0.11 or 1.1.0 does not work.

**Comment by tommyod** [comment]
It does exist:
https://pypi.org/project/KDEpy/1.0.10/

The error might be due to your python version not being 3.6, 3.7 or 3.8, which is what 1.0.10 is compiled to:
https://pypi.org/project/KDEpy/1.0.10/#files

But I'm not sure. Please check.

> Installing KDEpy 1.0.11 or 1.1.0 does not work.

What fails?

**Comment by AlexanderWMacFarlaneIV** [comment]
Thank you Tommyod.

That is it.
I am on Python 3.9.

When I said it fails I meant the pip install fails.
