### ISSUE TITLE
How to cite this package

### ISSUE THREAD

**Issue by jason1894** [tommyod/KDEpy#117]
Dear author:
  I have used this package in my academic paper, but i have no idea about how to cite it.Is there any message like bibtex item? 
Can you tell me how to cite it ? thanks

**Comment by syrte** [comment]
If you use bibtex, I guess you can cite it via zenodo like this 
```
@software{kdepy,
  title        = {KDEpy: Kernel Density Estimation in Python},
  author       = {Tommy Odland},
  year         = 2018,
  month        = dec,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.2392268},
  version      = {v0.9.10},
  %url         = {https://doi.org/10.5281/zenodo.2392268}
}
```
Wait for the author to confirm.

**Comment by jason1894** [comment]
ok,thank you very much! !

**Comment by tommyod** [comment]
That works, yes. Thanks a lot for responding @syrte
