### ISSUE TITLE
Return the value of bandwidth defined automatically with ISJ method

### ISSUE THREAD

**Issue by marco-rosso-m** [tommyod/KDEpy#120]
Hi, thanks for the python package it is the best and fast implementation of KDE in python. 

However, I was wondering if there is a simple way to return the value of the bandwidth automatically determined from the method ISJ or also from another method. I need to get this value and save it in a variable after run the FFTKDE command.

Thank you in advance

**Comment by KaizerJ** [comment]
I know this issue is closed but if anyone has the same question, you can access the class property bw after fitting:

`X = df['anything'].to_numpy().reshape(-1,1)
kde = FFTKDE(kernel='gaussian', bw='ISJ')
x, y = kde.fit(X).evaluate()

kde.bw`

**Comment by marco-rosso-m** [comment]
Yes, thank you very much! I had discovered how to access it after studying a little bit deeper you code.

It a very clear and fast code, all my sincerely admiration to your work!

Thank you very much anyway

Best regards


Marco Martino Rosso



ArtIStE - Artificial Intelligence in Structural Engineering<http://www.civilml.polito.it/>

e-mail: ***@***.******@***.***>

Personal Website<http://rossomarcomartino.flazio.com/>

PhD Student in Structural Civil Engineering at Politecnico di Torino

<https://aka.ms/AAb9ysg>
________________________________

**Comment by KaizerJ** [comment]
Im not author of this work, just had same question and wanted to make it easier to anyone who may have it in the future :)
