### ISSUE TITLE
Citation for your implementation

### ISSUE THREAD

**Issue by Dobberzoon** [tommyod/KDEpy#123]
Hi, 

Thank you for your great KDE tool, I am using it for my thesis. Do you have a suggested citation?

Greets,
Geomatics student from The Netherlands

**Comment by tommyod** [comment]
Hi! Great that you like the software. See the [bottom left of this website](https://zenodo.org/record/2392268) for citation information!

**Comment by Dobberzoon** [comment]
Super, thanks!
