### ISSUE TITLE
Add a JIT compiler? (feature request)

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [tommyod/KDEpy#125]
Hi, I wonder if there is a plan to use a JIT compiler to make it faster? There are some JIT compilers that are pretty easy to use, e.g., numba or Jax

**Comment by tommyod** [comment]
The slow parts are already written in cython, so I don't see how a JIT compiler would make it faster. So no, there is no such plan. If you are able to significantly speed up the code using a JIT compiler, then PRs are of course welcome.
