### ISSUE TITLE
Including KDEpy in BSD licensed project

### ISSUE THREAD

**Issue by whitews** [tommyod/KDEpy#129]
Hi Tommy,

I'm considering changing a KDE-based plotting function in my library (FlowKit, licensed under BSD) from seaborn to a Bokeh implementation using KDEpy. The performance difference is significant & I can get better contours using a box kernel in KDEpy. I didn't realize when I started testing that this project was licensed under GPL-3. I'm wondering if you would consider dual-licensing for specific cases?

Regards,
Scott

**Comment by tommyod** [comment]
Hi Scott! Sure. For use in the [FlowKit project](https://github.com/whitews/FlowKit), I give you permission to use KDEpy under the BSD License. That should be permissive enough to let you do whatever you want with it in the context of FlowKit. Does that work for you? Any formalities required?

**Comment by whitews** [comment]
Thanks Tommy! I will look into the formalities and get back to you. I wanted to simply ask first before taking the time to do so. If you are like me, delving into fine legal details is not exactly fun ;) I'm hoping it will be as easy as getting a pull request with the formal permission.

A long time ago when I got into Linux and discovered the world of open source software, I thought just put a GPL license on my work and we're good. Years later I was talking to a rep from a company we were collaborating with and they explained why they don't go near GPL code with a 10-foot pole. Up until then I didn't really understand what others meant about the "infectious" nature of the GPL. It makes sense for certain projects like the Linux kernel but for FlowKit I don't care if someone wants to bundle it in proprietary software or use it in a commercial project.

Thanks again for taking the time and your work on KDEpy!
-Scott

**Comment by tommyod** [comment]
Hi again Scott. For your information: I decided to change the license of the project. See PR https://github.com/tommyod/KDEpy/pull/131

Thanks a lot of raising this issue. I didn't know how restrictive the GPL was. I think it closes the issue for you :)

**Comment by whitews** [comment]
Thanks Tommy, this makes it easier to make the switch to KDEpy.

BTW, I encountered some issues installing on a Apple Silicon Mac & looks like others have as well (#114). After a little digging I think I may know what is happening there. I also have a project that uses C extensions and builds wheels for platforms, so I know it can be a pain. Anyway, I'll chime in on that issue if I can solve it.

Thanks again!
