### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by DHUZHANGSHUHE** [tommyod/KDEpy#130]
I'm having some problems importing the package.
from KDEpy import NaiveKDE, TreeKDE, FFTKDE
At the same time, can you give a detailed code example for the operation of the three-dimensional matrix.
As a beginner in machine learning, thank you for your pointers!

Best Wishes!

**Comment by tommyod** [comment]
It's not clear to me what you have tried, and what you're attempting to do.
