### ISSUE TITLE
how to get pseudo-uniform samples

### ISSUE THREAD

**Issue by suhasghorp** [tommyod/KDEpy#144]
Hello, I am new to KDE and KDEpy. I understand that KDE returns an empirical PDF for the data provided. I need to get a CDF from the PDF returned by KDEpy and then generate pseudo-samples for a Uniform distribution. I am basically trying to duplicate following R code which uses kcde fucntion from ks library.

```python
pseudo.samples = function(X){
    Fhat <- kcde(X) ## this directly returns CDF
    predict(Fhat,x=X)
}

pseudos = pseudo.samples(column_vector)
hist(pseudos)
``` 

Thank you.

**Comment by tommyod** [comment]
See [the documentation](https://kdepy.readthedocs.io/en/latest/examples.html#resampling-from-the-distribution)

If you want to do it as you sketch, do something like
```python
from KDEpy import FFTKDE
import numpy as np
data = np.random.randn(100)
x, y = FFTKDE().fit(data)()
cumulative = np.cumsum(y) / np.sum(y)

sample_idx = np.random.choice(np.arange(len(cumulative)), size=10)
cumulative[sample_idx]
```
