### ISSUE TITLE
cutils compiles to package parent directory

### ISSUE THREAD

**Issue by whitews** [tommyod/KDEpy#150]
Hi Tommy,

Doing some testing I came across a few issues. One is that the compiled cutils object is stored in the directory above the package directory. You can see this when installing via pip by looking in the site-packages directory:

<img width="966" alt="Screenshot 2023-09-17 at 7 06 45 PM" src="https://github.com/tommyod/KDEpy/assets/1298022/084b1ce4-dcae-4905-9bd9-58f075071e94">

I can submit a PR with a fix if you'd like.

-Scott

**Comment by tommyod** [comment]
Another good catch. Please do submit a PR. I'll happily merge!
