### ISSUE TITLE
Remove matplotlib dependency 

### ISSUE THREAD

**Issue by whitews** [tommyod/KDEpy#151]
Hi Tommy,

`matplotlib` is listed as an install dependency even though it is not imported by the package. It is used in the tests and the examples, but these can have their own dependency list that can be used for testing and the docs. Willing to provide a PR for this as well.

BTW, I noticed your docs build was failing. I'm not 100% sure but this might be due to an issue with nbsphinx 0.9.2. Version 0.9.3 is out now so maybe you can re-trigger the docs build in ReadTheDocs. RTD is nice but can be a real pain to troubleshoot.

Okay, that's all for now, hope all is well.
-Scott

**Comment by tommyod** [comment]
Good catch. Would definitely accept a PR to split up the dependencies!

> Version 0.9.3 is out now so maybe you can re-trigger the docs build in ReadTheDocs. RTD is nice but can be a real pain to troubleshoot.

Indeed. I'll look into this!
