### ISSUE TITLE
Calculate corresponding quantities

### ISSUE THREAD

**Issue by NSBTW** [tommyod/KDEpy#160]
I have a sample of values and for each value I have a real error. So I want to calculate a mean error and a standard deviation of the errors. I need to multiply the convolved values by the errors before integration. The errors can be negative, so I can't use weights for this. Anyway, I don't want to fit several times: with weights and without.

Is there a way to do this?

**Comment by tommyod** [comment]
Support for this is not included. Unless you find some way to reduce the computation to what is available through the API.
