### ISSUE TITLE
Compatibility with numpy 2

### ISSUE THREAD

**Issue by jonimatix** [tommyod/KDEpy#168]
Hi,

Can you please update the library to be compatible with numpy 2?

The below error is thrown when running:
`estimator.fit(df['amount'].values).evaluate(1000)`

`np.asfarray` was removed in the NumPy 2.0 release. Use `np.asarray` with a proper dtype instead.

Thanks

**Comment by tommyod** [comment]
> Can you please update the library to be compatible with numpy 2?

Very open to PRs if you, or anyone else, wants to have a go at it. :)

**Comment by tommyod** [comment]
Closed by #171
