### ISSUE TITLE
Installation on aarch64 linux fails

### ISSUE THREAD

**Issue by maxispeicher** [tommyod/KDEpy#177]
Trying to install `KDEpy` on arm64/aarch64 linux instances fails due to a chain of smaller issues:

1. `aarch64` `manylinux` wheels are not published on a release as wheels
2. `pip install kdepy` therefore tries to build the package from the `tar.gz` file
3. This however fails with `ValueError: 'KDEpy/cutils_ext/cutils.pyx' doesn't match any files`, which is correct as the published `tar.gz` file contains the `KDEpy/cutils_ext/cutils.c` file instead

Installing directly from github with e.g. `pip install https://github.com/tommyod/KDEpy/archive/refs/tags/v1.1.8.tar.gz` works just fine. So it's specifically about the `tar.gz` file published on pypi.

**Comment by tommyod** [comment]
I might look at this sometime in the future when I have more time. In the meantime, PRs are very welcome. Updating the CI/CD pipeline and build process would be a welcome change, if it can be made more clear and robust.

**Comment by maxispeicher** [comment]
I gave it an initial shot, mainly focusing on getting `aarch64` support without changing other parts of the logic. Also happy to adapt that if you have other plans.
