### ISSUE TITLE
Code to replicate comparison graphs

### ISSUE THREAD

**Issue by badbayesian** [tommyod/KDEpy#18]
Is the code to replicate the graphs on the [comparison page](https://kdepy.readthedocs.io/en/latest/comparison.html) available? I wasn't able to find it in the repo. I tried replicating a couple of the graphs on that page, however, I am getting different results. I'm not sure where the discrepancy lies. I have a [jupyter notebook](https://github.com/badbayesian/kde_examples/blob/master/testing_gaussian_dist.ipynb) comparing kdepy, statsmodels, and sklearn. Perhaps you might see why the comparison graphs differ?

**Comment by tommyod** [comment]
The code to replicate the graphs is available at [master/docs/source/profiling.py](https://github.com/tommyod/KDEpy/blob/master/docs/source/profiling.py). Here are the results of running that code on my computer just now, in the one-dimensional case.

![image](https://user-images.githubusercontent.com/10076072/53550742-d12ae480-3b37-11e9-9f23-a707366c88a1.png)

![image](https://user-images.githubusercontent.com/10076072/53550985-6037fc80-3b38-11e9-9677-1ebe456953ff.png)

The big discrepancy is that you're not evaluating the kernel density estimate of statsmodels and sklearn. If terms of the KDEpy API, you're *fitting*, but not *evaluating*. See [this example](https://scikit-learn.org/stable/auto_examples/neighbors/plot_kde_1d.html) for how to use the sklearn API.
