### ISSUE TITLE
Poor performance on 1D KDE

### ISSUE THREAD

**Issue by sursu** [tommyod/KDEpy#23]
Have you tried to replicate this [Simple 1D Kernel Density Estimation](https://scikit-learn.org/stable/auto_examples/neighbors/plot_kde_1d.html#sphx-glr-auto-examples-neighbors-plot-kde-1d-py)?

Here is my code:
```python
import numpy as np

from scipy import stats
from sklearn.neighbors.kde import KernelDensity
from KDEpy import FFTKDE, NaiveKDE, TreeKDE
import statsmodels.api as sm

import plotly.graph_objs as go
```

```python
N = 1000
xs = np.linspace(-5, 10, 1000)

m = np.concatenate((np.random.normal(0, 1, int(0.3 * N)), np.random.normal(5, 1, int(0.7 * N))))
true_dens = (0.3 * stats.norm(0, 1).pdf(xs) + 0.7 * stats.norm(5, 1).pdf(xs))


```

```python
fig = go.FigureWidget()
# True density
fig.add_scatter(x=xs, y=true_dens, 
                mode='lines', fill='tozeroy', fillcolor='lightgray',
                line=dict(color='black', width=2), 
                name='Input Distribution')

# Scipy
kernel = stats.gaussian_kde(m, bw_method='silverman')
fig.add_scatter(x=xs, y=kernel(xs), line=dict(width=1.5), name='Scipy')

# Scikit-Learn
kde = KernelDensity(kernel='gaussian', bandwidth=np.std(m)*(4/(3*len(m)))**(1/5),).fit(m[:,np.newaxis])
log_dens = kde.score_samples(xs[:,np.newaxis])
fig.add_scatter(x=xs, y=np.exp(log_dens), line=dict(width=1.5), name='SK-Learn')

# StatsModels
dens = sm.nonparametric.KDEUnivariate(m)
dens.fit()
fig.add_scatter(x=xs, y=dens.evaluate(xs), line=dict(width=1.5), name='StatsModels')

# KDEpy
x, y = FFTKDE(kernel='gaussian', bw='silverman').fit(m, weights=np.arange(len(m)) + 1)(2**15)
fig.add_scatter(x=x, y=y, line=dict(width=1.5), name='FFTKDE')

# Rugplot
fig.add_scatter(x=m, y=np.zeros(len(m))-0.01, 
                mode='markers', showlegend=False,
                marker=dict(symbol='line-ns-open', color='black')) 

fig.layout.update(xaxis=dict(zeroline=False))
fig
```
![image](https://user-images.githubusercontent.com/12001304/57968607-1c9da380-796d-11e9-8578-8d0670c360a1.png)

It looks like the FFT estimation is not that good.
Am I doing something wrong? Or what are the caveats one should consider when dealing with FFTKDE?

**Comment by tommyod** [comment]
Thanks for raising this Issue @sursu .

I immediately notice two things:
- You are setting `weights` to weight data points like `[1, 2, 3, ...]` when you pass `weights=np.arange(len(m)) + 1`. This causes the KDE to assign more weights to the points on the right hand side of the plot compared to the left hand side. You see this on the graph since the density is overestimated on the right, and underestimated on the right. Scipy, sklearn and scipy do not support data point weighting, so you should not use in with FFTKDE either if you want to results to match.
- You evaluate the FFTKDE on `2**15 ~ 32768` grid points, while evaluating the others on `xs`, which contains `1000` grid points.

Try this:
```
y = FFTKDE(kernel='gaussian', bw='silverman').fit(m, weights=None).evaluate(xs)
fig.add_scatter(x=xs, y=y, line=dict(width=1.5), name='FFTKDE')

```

Let me know how it goes. I have tested against the other implementations.

**Comment by sursu** [comment]
They do indeed match indistinguishably!
Thank you!

My impression was that: the finer the grid the better the approximation (that's why I chose such a fine grid); and from the [example code](https://kdepy.readthedocs.io/en/latest/#example-code) that weighted fitting gives better results.

**Comment by tommyod** [comment]
Great! If you increase `N` you will see that KDEpy is fast for a millions points :+1:

I should re-write the docs and make it more clear:
- The finer the grid the better the approximation: but `1000` grid points is more than enough!
- The purpose of the weights is to weight the data points in relevant scenarios, for but an ordinary KDE the choice `weights=None` is correct.
