### ISSUE TITLE
FFTKDE.evaluate on one single point

### ISSUE THREAD

**Issue by davidggphy** [tommyod/KDEpy#25]
Hello,

What is the best way of evaluating FFTKDE on a single point? Do I need to create a grid containing it in order to use the evaluate method?

Thanks in advance!

**Comment by tommyod** [comment]
The following should work:
```python
x, y = FFTKDE(bw=1).fit([1]).evaluate() 
```
Hope that helps! :+1:

**Comment by davidggphy** [comment]
Thanks for the fast answer @tommyod , but what I meant is that I want only to evaluate on one point, but I am fitting my KDE on another set of points. This is, I want to estimate my probability distribution function (pdf) given a set of samples, and then evaluate the pdf on another point (a single one, not a grid). I can easily do it with KDEpy.TreeKDE, but not with KDEpy.FFTKDE.

**Comment by tommyod** [comment]
I understand. You'll have to either use TreeKDE, or use a grid and then single out a specific point. The accuracy  of FFTKDE depends on the number of grids point (the more the better, but 64 or 128 will be very accurate). Two options:
1. Use TreeKDE
2. Use FFTKDE with a grid going from x - d, to x +d, the single out the middle value of the grid.

If you want to evaluate it on a point not in the original grid you'll have to interpolate. FFTKDE is amazingly fast and accurate, but the downside is that it requires an equidistant grid with a few grid points.

Hope this helps. Let me know if you have trouble / figure it out. :+1:
