### ISSUE TITLE
Tried to install KDEpy on my mac but doesn't work.  Error code below

### ISSUE THREAD

**Issue by sunnyluo1993** [tommyod/KDEpy#32]
(base) usertekiAir:~ user$ pip install KDEpy
Collecting KDEpy
  Using cached https://files.pythonhosted.org/packages/c9/ff/0229a6cb3df501d2c1908b6a1c036389e695d4f888c502191471e3f2003e/KDEpy-1.0.2.tar.gz
Requirement already satisfied: numpy>=1.14.2 in /Applications/anaconda3/lib/python3.7/site-packages (from KDEpy) (1.16.2)
Requirement already satisfied: scipy>=1.0.1 in /Applications/anaconda3/lib/python3.7/site-packages (from KDEpy) (1.2.1)
Requirement already satisfied: matplotlib>=2.2.0 in /Applications/anaconda3/lib/python3.7/site-packages (from KDEpy) (3.0.3)
Requirement already satisfied: cycler>=0.10 in /Applications/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2.0->KDEpy) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Applications/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2.0->KDEpy) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Applications/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2.0->KDEpy) (2.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /Applications/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2.0->KDEpy) (2.8.0)
Requirement already satisfied: six in /Applications/anaconda3/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=2.2.0->KDEpy) (1.12.0)
Requirement already satisfied: setuptools in /Applications/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2.0->KDEpy) (40.8.0)
Building wheels for collected packages: KDEpy
  Building wheel for KDEpy (setup.py) ... error
  Complete output from command /Applications/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-install-kx7v8okg/KDEpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-wheel-rffy7dys --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/binning.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/kernel_funcs.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/FFTKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/TreeKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/NaiveKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/BaseKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/bw_selection.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  copying KDEpy/utils.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
  running build_ext
  skipping 'KDEpy/cutils.c' Cython extension (up-to-date)
  building 'cutils' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/KDEpy
  x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Applications/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Applications/anaconda3/include/python3.7m -c KDEpy/cutils.c -o build/temp.macosx-10.9-x86_64-3.7/KDEpy/cutils.o
  In file included from KDEpy/cutils.c:4:
  /Applications/anaconda3/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  1 error generated.
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for KDEpy
  Running setup.py clean for KDEpy
Failed to build KDEpy
Installing collected packages: KDEpy
  Running setup.py install for KDEpy ... error
    Complete output from command /Applications/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-install-kx7v8okg/KDEpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-record-hd16kmky/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/binning.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/kernel_funcs.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/FFTKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/TreeKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/NaiveKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/BaseKDE.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/bw_selection.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    copying KDEpy/utils.py -> build/lib.macosx-10.9-x86_64-3.7/KDEpy
    running build_ext
    skipping 'KDEpy/cutils.c' Cython extension (up-to-date)
    building 'cutils' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/KDEpy
    x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Applications/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Applications/anaconda3/include/python3.7m -c KDEpy/cutils.c -o build/temp.macosx-10.9-x86_64-3.7/KDEpy/cutils.o
    In file included from KDEpy/cutils.c:4:
    /Applications/anaconda3/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
    
    ----------------------------------------
Command "/Applications/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-install-kx7v8okg/KDEpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-record-hd16kmky/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kh/55sgb3353t36wpt0l6_p1y840000gn/T/pip-install-kx7v8okg/KDEpy/

**Comment by sunnyluo1993** [comment]
I tried the method of installing in different environment you provided for other people and got the same issue

**Comment by tommyod** [comment]
Looking into this. Will get back to you @sunnyluo1993

**Comment by tommyod** [comment]
@sunnyluo1993 Built files should be on pypi now. Can you try running `pip install KDEpy --no-cache-dir`again?

**Comment by sunnyluo1993** [comment]
@tommyod a simple pip install KDEpy works now.  Thank you for your help!
