### ISSUE TITLE
name 'norm' is not defined

### ISSUE THREAD

**Issue by YanXiee** [tommyod/KDEpy#41]
Hi, when I ran the example code 'from KDEpy import FFTKDE
data = norm(loc=0, scale=1).rvs(2**3)
estimator = FFTKDE(kernel='gaussian', bw='silverman')
x, y = estimator.fit(data, weights=None).evaluate()
plt.plot(x, y, label='KDE estimate')' after installation, it says 'NameError: name 'norm' is not defined'. How should I deal with that? Thank you!

**Comment by tommyod** [comment]
From scipy.stats import norm.

**Comment by tommyod** [comment]
This is in the text above the example, but could be more clear.

**Comment by YanXiee** [comment]
> This is in the text above the example, but could be more clear.

Thank you so much.
