### ISSUE TITLE
Possible typo in docs regarding complexity of FFTKDE

### ISSUE THREAD

**Issue by rdimaio** [tommyod/KDEpy#47]
Hi,

In FFTKDE's docs (https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE), the time complexity for the first phase is given as O(N*(2^d)) and for the second phase as (Onlogn); the total running time is then given as O(N(d^2)+nlogn). I am not sure if the N(d^2) in the total running time is a typo  (d^2 instead of 2^d) or if I am just misunderstanding something. Thank you again for implementing this, by the way! It's extremely useful 😄

**Comment by tommyod** [comment]
You are correct! It should be 2 to the power of d. You are welcome to create a PR!
