### ISSUE TITLE
Why I get so big difference?

### ISSUE THREAD

**Issue by GF-Huang** [tommyod/KDEpy#50]
```py
import numpy
from scipy import stats
import matplotlib.pyplot as plt
import KDEpy

a = numpy.sort([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.7, 1])
```

```py
x, y = KDEpy.FFTKDE().fit(a).evaluate(len(a))
plt.plot(x, y)
```
![image](https://user-images.githubusercontent.com/4510984/81489491-9c243100-92a8-11ea-8e43-0fa81be345a2.png)

```py
plt.plot(a, stats.gaussian_kde(a).evaluate(a))
```
![image](https://user-images.githubusercontent.com/4510984/81489500-c0800d80-92a8-11ea-8eac-49d920c46bef.png)

**Comment by syrte** [comment]
As far as I see, the output is reasonable.

Two comments:
1. It would be a more fair comparison if specifying the same bandwidth for KDEpy and Scipy.
2. You should use `plt.plot(x, stats.gaussian_kde(a).evaluate(x))` for Scipy if you are asking why the x range is different.

**Comment by GF-Huang** [comment]
Why `stats.gaussian_kde(a).evaluate(x)`, not `stats.gaussian_kde(a).evaluate(a)`?

**Comment by tommyod** [comment]
Good insight by @syrte , I agree with the comments.

Your scipy code says "evaluate the KDE on the exact data points" (you also pass duplicate data points in `a`, which does not make much sense). If you wanted to evaluate the density on the exact data points, why not just count repeated measurements?

The KDEpy code says "evaluate on `len(a)` equidistant grid points, and please create the grid for me". This is more reasonable usage for a KDE than evaluating exactly on the data points. Still the grid is quite coarse.

If you (1) create a common grid with `np.linspace(-5, 5, 2**10)` and (b) choose the same bandwidth, you will get the same results. See [the docs](https://kdepy.readthedocs.io/en/latest/API.html#fftkde) for more information.

**Comment by GF-Huang** [comment]
Sorry, I am a newbie in statistics. 
I have a one-dimensional array with 15,000,000 data points, I want to calculate the PDF and CDF by KDE, could you tell me what's the correct way? 
Thank you!

**Comment by syrte** [comment]
@GF-Huang it sounds like that you want the PDF on a grid rather than the PDF on each point. So you can make a grid that covers the range of the points (e.g., `np.linspace(a.min(), a.max(), ngrid)`. Then evaluate the PDF on this grid `y=KDEpy.FFTKDE().fit(a).evaluate(x)`. Or simply `x, y = KDEpy.FFTKDE().fit(a).evaluate(ngrid)`. ngrid=1000 would be good enough for most cases I guess.
I'm wondering if Scipy can handle such a large number of points with reasonable time and memory usage.

**Comment by tommyod** [comment]
I agree with the good points raised by @syrte . Scipy is likely way too slow (but feel free to try). The following code should work. It's taken more or less directly from the README, and will create a grid with 2**10 points.
```python
x, y = FFTKDE(kernel="gaussian", bw="silverman").fit(customer_ages).evaluate()
plt.plot(x, y)
y_cdf = np.cumsum(y) # Compute CDF
y_cdf = y_cdf / y_cdf[-1] # Normalize
plt.plot(x, y_cdf)
```

Beware of outliers, missing data (null values), etc. If 15 million points are too slow, you could sample ( say 1 million points) at random without replacement and fit the KDE to the sampled data points. Good luck! I will close this issue, but feel free to discuss further if needed.

**Comment by GF-Huang** [comment]
What the mean of "Grid" in this sence?

**Comment by tommyod** [comment]
The variable `x`.

**Comment by GF-Huang** [comment]
Got it, thank you all. 🌹

**Comment by GF-Huang** [comment]
> I'm wondering if Scipy can handle such a large number of points with reasonable time and memory usage.

I don't think scipyt can process 15,000,000 data points in an acceptable time.

![image](https://user-images.githubusercontent.com/4510984/81511203-283a6500-934a-11ea-8dc8-12f969defa89.png)
