### ISSUE TITLE
KDE for 2dim irregular data (not grid)

### ISSUE THREAD

**Issue by PawanGu** [tommyod/KDEpy#53]
Hi,
Here is reference given for 2d kernel, but only in case of grid data.
https://kdepy.readthedocs.io/en/latest/kernels.html#higher-dimensional-kernels

I found that if there is random 2d data set is given. KDEpy does not seem to find the consistent kde, as I compared with scipy_gaussian_kde. It also does not satisfy the normalisation condition.

Here chi0 chi1 have random value b/w 0 and 1. 
kernel = BaseKDE._available_kernels['gaussian']
values = np.transpose(np.vstack([chi0, chi1]))
z = kernel(values, norm=2)
This z is not normalised.

Can I make function from KDEpy just like scipy_gaussian_kde ?
X, Y = np.mgrid[xmin:xmax:100j, ymin:ymax:100j]
positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([m1, m2])
kernel = stats.gaussian_kde(values)
here kernel is function.

Thank you.

**Comment by tommyod** [comment]
The linked example is only there to create the specific figure under it. It was not meant as a general approach. The line `BaseKDE._available_kernels['gaussian']` fetches a low level function from an abstract base class. 

Use the `FFTKDE` as described [in this example](https://kdepy.readthedocs.io/en/latest/examples.html#the-effect-of-norms-in-2d) instead!
