### ISSUE TITLE
Where can I find an example for n- dimensional kernel regression using FFTKDE??I tried the below 3-d multiple regression but having difficulty interpreting the output.

### ISSUE THREAD

**Issue by AspirnQnt** [tommyod/KDEpy#54]
#The data to be analysed is of shape 506*3 dataframe
from KDEpy import FFTKDE
crim=np.array(crim)
rm=np.array(rm)
medv=np.array(medv)
#The data to be analysed is of shape 506*3 dataframe
weights=np.vstack([crim,rm,medv])
print(weights.shape)

grid1,points1 = FFTKDE(bw=0.5).fit(weights.T).evaluate()
x1, y1 = np.unique(grid1[:, 0]), np.unique(grid1[:, 1])
print(len(x1))
z = points1.reshape(100, 10)
y_pred =  np.sum((z.T / np.sum(z, axis=1)).T  * y1 , axis=1)
print(y_pred)

**Comment by tommyod** [comment]
I don't think I wrote an example for more than 2D or 3D. I'm not sure what you're asking exactly.

- What specifically about the output makes it difficult to interpret?
- How would you like to interpret n-dimensional kernel regression? What do you mean by "interpret"?

**Comment by AsPiRInQNT** [comment]
Thank you for the response.An example of kernel regression using FFTKDE for more than 2D or 3D is exactly what I needed for reference.

**Comment by jason1894** [comment]
Hello,have you get the referenc 2D or 3D ? could you show me how to make it ? thanks very much!

**Comment by tommyod** [comment]
https://kdepy.readthedocs.io/en/latest/examples.html#the-effect-of-norms-in-2d
