### ISSUE TITLE
The output has different dimensiones to the input data

### ISSUE THREAD

**Issue by suzannejin** [tommyod/KDEpy#55]
I would like to determine the KDE for each point of my data. However, the output produced by FFTKDE has always 1024 rows, in contrast to other implementations (Eg. the gaussian_kde from scipy). Is there a way to produce similar results as the gaussian_kde implementation?

An example code:
```
from KDEpy import FFTKDE
from scipy.stats import gaussian_kde

# Data
customer_ages = [40, 56, 20, 35, 27, 24, 29, 37, 39, 46]
customer_income = [152, 64, 24, 140, 88, 64, 103, 148, 150, 132]
x = customer_ages
y = customer_income

# Scipy gaussian_kde
xy = np.vstack([customer_ages,customer_income])
out = gaussian_kde(xy)(xy)
print('Scipy: gaussian_kde\n-------------------')
print('1 output, with shape ' + str(out.shape))
print(out)

# KDEpy FFTKDE
customer_2d = np.array([customer_ages, customer_income]).transpose()
out = FFTKDE(kernel="gaussian").fit(customer_2d).evaluate()
print('\nKDEpy: FFTKDE\n-------------')
print('2 output, x' + str(out[0].shape) + ' and y' + str(out[1].shape))
print(out[0])
print(out[1])
```

And the output:
```
Scipy: gaussian_kde
-------------------
1 output, with shape (10,)
[3.35135483e-04 7.71774462e-05 1.21084195e-04 3.46854720e-04
 2.49810866e-04 2.06022906e-04 2.74664480e-04 3.47653843e-04
 3.45484771e-04 1.81037600e-04]

KDEpy: FFTKDE
-------------
2 output, x(1024, 2) and y(1024,)
[[ 15.92684001  17.6       ]
 [ 15.92684001  22.14193548]
 [ 15.92684001  26.68387097]
 ...
 [ 60.07315999 149.31612903]
 [ 60.07315999 153.85806452]
 [ 60.07315999 158.4       ]]
[2.22044605e-16 2.27673700e-05 1.57620254e-05 ... 2.22044605e-16
 2.22044605e-16 2.22044605e-16]
```

**Comment by tommyod** [comment]
> I would like to determine the KDE for each point of my data.

FFTKDE is much faster than scipy, but it's because of a gradeoff in the implementation. From the [FFTKDE docs](https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE):

> This class implements a convolution (FFT) based computation of a KDE. While this implementation is very fast, there are some limitations: (1) the bandwidth must be constant, **(2) the KDE must be evaluated on an equidistant grid and** (3) the grid must encompass every data point. The finer the grid, the smaller the error.

You can increase the number of grid points, or use a custom grid (but it must be equidistant). See the [documentation of the .evaluate() method](https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE.evaluate).

Something like this should do the trick:
```python
grid_points = [64, 128] # 64 grid points in first dimension, 128 in second
out = FFTKDE(kernel="gaussian").fit(customer_2d).evaluate(grid_points)

grid_points = 64 # 64 grid points in both dimensions
out = FFTKDE(kernel="gaussian").fit(customer_2d).evaluate(grid_points)
```


For almost every practical purpose (e.g. plotting), 1024 grid points should be more than enough and the fact that the grid is equidistant does not matter. 1024 was chosen as the default because a monitor is often 1080 pixels wide, so even a full-screen plot of a KDE will have negligible error due to grid point interpolation. Again, this is for most use cases :)

Let me know if you have any other questions. The TreeKDE allows arbitrary grid points, but is not as fast as FFTKDE.

**Comment by suzannejin** [comment]
This is very useful. Thank you for the quick response : )

> > I would like to determine the KDE for each point of my data.
> 
> FFTKDE is much faster than scipy, but it's because of a gradeoff in the implementation. From the [FFTKDE docs](https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE):
> 
> > This class implements a convolution (FFT) based computation of a KDE. While this implementation is very fast, there are some limitations: (1) the bandwidth must be constant, **(2) the KDE must be evaluated on an equidistant grid and** (3) the grid must encompass every data point. The finer the grid, the smaller the error.
> 
> You can increase the number of grid points, or use a custom grid (but it must be equidistant). See the [documentation of the .evaluate() method](https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE.evaluate).
> 
> Something like this should do the trick:
> 
> ```python
> grid_points = [64, 128] # 64 grid points in first dimension, 128 in second
> out = FFTKDE(kernel="gaussian").fit(customer_2d).evaluate(grid_points)
> 
> grid_points = 64 # 64 grid points in both dimensions
> out = FFTKDE(kernel="gaussian").fit(customer_2d).evaluate(grid_points)
> ```
> 
> For almost every practical purpose (e.g. plotting), 1024 grid points should be more than enough and the fact that the grid is equidistant does not matter. 1024 was chosen as the default because a monitor is often 1080 pixels wide, so even a full-screen plot of a KDE will have negligible error due to grid point interpolation. Again, this is for most use cases :)
> 
> Let me know if you have any other questions. The TreeKDE allows arbitrary grid points, but is not as fast as FFTKDE.
