### ISSUE TITLE
Problem in understanding

### ISSUE THREAD

**Issue by ankitkr1606** [tommyod/KDEpy#56]
I'm trying to find the kernel density of 2D Data points but when I'm trying to sum up all the points probability it's not getting sum up to 1 or even close. Sometimes it is going above 1 too. Can you please explain this?

**Comment by tommyod** [comment]
The integral sums to one, not the sum of the sampled function values. 

For instance, a box function on [0, 1] integrates to one. But if you sample it at equidistant 10 points on [0,1] you get (1, 1, ..., 1) - which sums to 10, not one.

Read up on probability density functions. If you believe there is a bug in the software, please provide a minimal working example.
