### ISSUE TITLE
Problems with fitting a KDE to a sine curve

### ISSUE THREAD

**Issue by Eequla** [tommyod/KDEpy#57]
Hello, as a small test to visualize the important of bandwidth in a KDE I plotted a sine curve until 2*pi and create 500 data points around the sine curve with some noise. However, when I try to do the KDE it gives me a very strange result which does not resemble a sine curve at all. Below is all the code the first part generates the sine graph with a scatter plot. I used the example 'Boundary correction using mirroring' without it it still gives a very weird result. The end result is the graph in the last picture which in theory should closely resemble a sine curve.

I am clearly doing something wrong here but I cannot figure out what perhaps I am entirely misunderstanding what the FFTKDE function does and not using it for its intended purpose.  
![image](https://user-images.githubusercontent.com/69016723/88975583-b9bad280-d2ba-11ea-91e2-c6e02c958532.png)
![image](https://user-images.githubusercontent.com/69016723/88975451-7f513580-d2ba-11ea-9099-acd659f822a2.png)
![image](https://user-images.githubusercontent.com/69016723/88975811-3057d000-d2bb-11ea-80c0-c816daa4469e.png)

**Comment by tommyod** [comment]
> I am clearly doing something wrong here but I cannot figure out what perhaps I am entirely misunderstanding what the FFTKDE function does and not using it for its intended purpose.

**I believe you are trying to do "kernel regression", not "kernel density estimation".** KDEpy does the latter, not the former :) Please see the wikipedia entries for these two concepts for an explanation of the differences between the two methods. There are some similarities, which I explore [in this example](https://kdepy.readthedocs.io/en/latest/examples.html#one-dimensional-kernel-regression). However, if you want to do kernel regression, I suggest using some other Python library for that task.

Hope that helps. Let me know.
