### ISSUE TITLE
Bandwidth: why are 'scott' and 'silverman' not available except for 1D data?

### ISSUE THREAD

**Issue by Gabriel-p** [tommyod/KDEpy#59]
In [scipy.stats.gaussian_kde](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) both these methods are available for multi-dimensional data, I believe.

Why are they only available for 1D data here?

BTW: is the bandwidth value used by `KDEpy` equivalent to the one used in `gaussian_kde`?

**Comment by tommyod** [comment]
Short answer: implementation choices and details. Longer answer: scipy only allows gaussian kernels, and uses a completely different algorithm. In KDEpy every kernel function is a one dimensional radial basis function. In a gaussian kernel, the covariance matrix can be used to scale and rotate the KDE. It's not obvious to me how the scott and silverman rules extend to higher dimensions for arbitrary kernel functions that are radial basis functions. If you know how to do it, please refer me to litterature or write a PR! I'm not against it, but I don't think it's trivial.

As for the second question, I think the meaning of bandwith is well documented in both libraries. I don't know on the top of my head, so I can only refer you to the docs. In KDEpy the BW is the standard deviation of the kernel function.

**Comment by Gabriel-p** [comment]
> scipy only allows gaussian kernels

Didn't think of this.

After some reading, I found that the bandwidth in scipy is weighted by the covariance. So to use an equivalent bandwidth in KDEpy I have to use:

    bw = kde.covariance_factor() * sample.std()

(where `kde` is from `gaussian_kde`)

**Comment by tommyod** [comment]
Yea! I seem to remember something like that. 👍 (It's been a while since I looked at the docs.)
