### ISSUE TITLE
How to resample data points from a kde model?

### ISSUE THREAD

**Issue by websitefingerprinting** [tommyod/KDEpy#62]
Hi! I just wonder whether KDEpy provides any API for sampling data points from a fitted kde model?

**Comment by tommyod** [comment]
Just sample from the original data points and add gaussian noise with bandwidth equal to the variance of the kernel. It's an equivalent operation. E.g. fit KDE and obtain bw, use `np.random.choice` to sample, then use `np.random.randn` to add noise.

**Comment by tommyod** [comment]
By the way, if you create a PR with a little example showing this for the docs (here: https://github.com/tommyod/KDEpy/blob/master/docs/source/examples.rst) it would be appreciated.
