### ISSUE TITLE
Can't install KDEpy 1.0.5  on Windows Anaconda environment

### ISSUE THREAD

**Issue by alexandrakisin** [tommyod/KDEpy#63]
I have the latest anaconda environment on my Windows machine. 
```
 conda list anaconda
# packages in environment at C:\ProgramData\Anaconda3\envs\testkisin:
#
# Name                    Version                   Build  Channel
anaconda                  2020.07                  py38_0
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.4                      py_0
```
Python is 3.8.3
Conda version 4.8.5
Pip version 20.2.3
Trying to install the latest KDEpy 1.0.5 and got the error :
```
pip install KDEpy==1.0.5
ERROR: Could not find a version that satisfies the requirement KDEpy==1.0.5 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6, 0.6.9, 0.6.10, 0.6.11, 1.0.2, 1.0.3)
ERROR: No matching distribution found for KDEpy==1.0.5
```
Doing the same in Linux exactly identical environment without any problems. 
What can be the problem ? The latest KDEpy is not available for Windows ? 

Thank you.

**Comment by tommyod** [comment]
Seems like the 1.0.5 version did not build for Windows. I'll look into it.

Can you try `pip install KDEpy==1.0.3` in the meantime? It should work. Let me know if it doesn't.

**Comment by tommyod** [comment]
:heavy_check_mark: Should be built on 1.0.5 now. Please try again and verify.

**Comment by alexandrakisin** [comment]
It is working now. I succeed to install version 1.0.5
Thank you for such prompt response!
