### ISSUE TITLE
FFTKDE on a fix (equidistant) grid

### ISSUE THREAD

**Issue by francoislauger** [tommyod/KDEpy#64]
I was wondering if there was a way to evaluate FFTKDE on a fix grid. For example, to evaluate the kernel on a grid of 256 points between -2 and 2.  And the same thing for more thant 1 dimension, ex. 256 points in x0 between -2 and 2 and 256 between -1 and 1 in x1.

**Comment by tommyod** [comment]
Sure, take [a look at the docs](https://kdepy.readthedocs.io/en/latest/API.html#KDEpy.FFTKDE.FFTKDE.evaluate). Let me know if it's unclear.

**Comment by francoislauger** [comment]
Thanks for the quick respond.

Perhaps I'm missing something in the doc but what I'm trying to do is something like that my real data generation process  is not a random normal ) :
```Python
from KDEpy import FFTKDE
import numpy as np
x = np.random.normal(0,1,10000)
x_density_1,y_density_1= FFTKDE(bw=.01, kernel='epa').fit(x).evaluate((256))

x = np.random.normal(0,1,10000)
x_density_2,y_density_2 = FFTKDE(bw=.01, kernel='epa').fit(x).evaluate((256))
print(x_density_1[0],x_density_2[0])
##Print : **-4.256483376118416 4.630142239000812**
```

At the end I want to calculate the distance between  y value at each point of the density (ex. `y_density_1[0]-y_density_2[0]`). But these points need to be at the same place on the grid. I need to have the same grid, not just the same number of points. I want to fix the min and max of the grid (I can drop the rare observations that are outside of these points if needed).For context I'm doing some minimization and I will do something like  `(y_density_1-y_density_2 )'*W*(y_density_1-y_density_2 )`

**Comment by tommyod** [comment]
The linked docs say you can use (array-like, int, tuple or None), so you can use a grid like so:

```python
x_grid = np.linspace(-10, 10, num=2**10)
y_density_1= FFTKDE(bw=.01, kernel='epa').fit(x).evaluate(x_grid)
y_density_2 = FFTKDE(bw=.01, kernel='epa').fit(x).evaluate(x_grid)
```

This might not be clear from the docs. I have updated the docs with this example:


```python
        >>> kde = FFTKDE().fit([1, 3, 4, 7])
        >>> # Three ways to evaluated:
        >>> x, y = kde.evaluate()  # (1) Auto grid
        >>> x, y = kde.evaluate(256)  # (2) Auto grid with 256 points
        >>> # (3) Use a custom grid (make sure it's wider than the data)
        >>> x_grid = np.linspace(-10, 25, num=2**10)
        >>> y = kde.evaluate(x_grid)
```

Does it work for you now? Do you think the docs are more clear now? If not, feel free to submit a PR :)

**Comment by francoislauger** [comment]
Thanks a lot.

With your exemple I realised that I put x,y = ... with the grid even if it's suppose to be just y (as it's well stated in the documentation).
