### ISSUE TITLE
Bandwidth not recalculated with multiple calls to fit

### ISSUE THREAD

**Issue by psederberg** [tommyod/KDEpy#78]
We recently ran into an issue when setting up an FFTKDE object once and calling `fit` more than once on the same object with different data. It seems as though the `bw` is not recalculated after the first call to fit because it is set to the `self.bw`, so that it isn't overwritten. This can give rise to some serious errors in the density estimates.

Here is some code that illustrates the issue:

```python
from KDEpy import FFTKDE
import matplotlib.pyplot as plt
import numpy as np

# set up plotting range and generate some data
xrng = np.linspace(-100, 100, 2048)
x = np.random.randn(1000)
xs = x*25

# set up the KDE
kernel = 'epa'
bw = 'ISJ'
kde = FFTKDE(kernel=kernel, bw=bw)

# do an initial fit on non-scaled data
p = kde.fit(x).evaluate(xrng)

# do another with a different scale and plot the results
p = kde.fit(xs).evaluate(xrng)
plt.plot(xrng, p)

# plot what the correct answer should be
p2 = FFTKDE(kernel=kernel, bw=bw).fit(xs).evaluate(xrng)
plt.plot(xrng, p2)
```

![image](https://user-images.githubusercontent.com/5210/100279042-d054fb80-2f33-11eb-9866-ff8f36c2bce8.png)

It seems to me that a fix in BaseKDE would correct this if `self.bw` wasn't overwritten with the value the first call to `fit`.

I hope this example helps track down the issue. I think that the behavior I demonstrate above is not what you'd want to do (I've worked around it my code by recreating the FFTKDE object each time), but please let me know if I'm incorrect.

Thanks for a great library!
Per

**Comment by tommyod** [comment]
Thanks for the detailed bug report @psederberg . Seems like you're correct. Want to submit a PR? If not I'll have a look at it when I get the chance 👍

**Comment by psederberg** [comment]
Awesome fix, thank you!

**Comment by tommyod** [comment]
Beware that it's not on uploaded to pypi yet, so please create a new KDE object for each fit - for now :)

**Comment by psederberg** [comment]
Will do, and I'll report back if we see any issues once it's migrated to
pypi. Thanks again!
