### ISSUE TITLE
Installation fails in python 3.9

### ISSUE THREAD

**Issue by mbr085** [tommyod/KDEpy#83]
Here is the output from pip install KDEpy

Collecting KDEpy
  Using cached KDEpy-1.0.2.tar.gz (136 kB)
Requirement already satisfied: numpy>=1.14.2 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from KDEpy) (1.19.4)
Requirement already satisfied: scipy>=1.0.1 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from KDEpy) (1.5.4)
Requirement already satisfied: matplotlib>=2.2.0 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from KDEpy) (3.3.3)
Requirement already satisfied: cycler>=0.10 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from matplotlib>=2.2.0->KDEpy) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from matplotlib>=2.2.0->KDEpy) (2.8.1)
Requirement already satisfied: numpy>=1.14.2 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from KDEpy) (1.19.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from matplotlib>=2.2.0->KDEpy) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from matplotlib>=2.2.0->KDEpy) (8.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from matplotlib>=2.2.0->KDEpy) (2.4.7)
Requirement already satisfied: six in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=2.2.0->KDEpy) (1.15.0)
Requirement already satisfied: six in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=2.2.0->KDEpy) (1.15.0)
Requirement already satisfied: numpy>=1.14.2 in /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages (from KDEpy) (1.19.4)
Building wheels for collected packages: KDEpy
  Building wheel for KDEpy (setup.py): started
  Building wheel for KDEpy (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_feitbkb
       cwd: /tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/
  Complete output (156 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/binning.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/bw_selection.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/kernel_funcs.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/utils.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/BaseKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/FFTKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/NaiveKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/__init__.py -> build/lib.linux-x86_64-3.9/KDEpy
  copying KDEpy/TreeKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  skipping 'KDEpy/cutils.c' Cython extension (up-to-date)
  building 'cutils' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/KDEpy
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages/numpy/core/include -I/home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/include -I/usr/include/python3.9 -c KDEpy/cutils.c -o build/temp.linux-x86_64-3.9/KDEpy/cutils.o
  KDEpy/cutils.c: In function ‘__Pyx_modinit_type_init_code’:
  KDEpy/cutils.c:18644:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  18644 |   __pyx_type___pyx_array.tp_print = 0;
        |                         ^
  KDEpy/cutils.c:18649:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  18649 |   __pyx_type___pyx_MemviewEnum.tp_print = 0;
        |                               ^
  KDEpy/cutils.c:18664:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  18664 |   __pyx_type___pyx_memoryview.tp_print = 0;
        |                              ^
  KDEpy/cutils.c:18677:35: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  18677 |   __pyx_type___pyx_memoryviewslice.tp_print = 0;
        |                                   ^
  KDEpy/cutils.c: In function ‘__Pyx_ParseOptionalKeywords’:
  KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19320:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19320:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  KDEpy/cutils.c: In function ‘__Pyx_decode_c_string’:
  KDEpy/cutils.c:20396:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
  20396 |         return PyUnicode_FromUnicode(NULL, 0);
        |         ^~~~~~
  In file included from /usr/include/python3.9/unicodeobject.h:1026,
                   from /usr/include/python3.9/Python.h:97,
                   from KDEpy/cutils.c:4:
  /usr/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
    551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
        |                                          ^~~~~~~~~~~~~~~~~~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for KDEpy
  Running setup.py clean for KDEpy
Failed to build KDEpy
Installing collected packages: KDEpy
    Running setup.py install for KDEpy: started
    Running setup.py install for KDEpy: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rx_8z9nx/install-record.txt --single-version-externally-managed --compile --install-headers /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/include/site/python3.9/KDEpy
         cwd: /tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/
    Complete output (156 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/binning.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/bw_selection.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/kernel_funcs.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/utils.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/BaseKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/FFTKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/NaiveKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/__init__.py -> build/lib.linux-x86_64-3.9/KDEpy
    copying KDEpy/TreeKDE.py -> build/lib.linux-x86_64-3.9/KDEpy
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    skipping 'KDEpy/cutils.c' Cython extension (up-to-date)
    building 'cutils' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/KDEpy
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/lib/python3.9/site-packages/numpy/core/include -I/home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/include -I/usr/include/python3.9 -c KDEpy/cutils.c -o build/temp.linux-x86_64-3.9/KDEpy/cutils.o
    KDEpy/cutils.c: In function ‘__Pyx_modinit_type_init_code’:
    KDEpy/cutils.c:18644:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
    18644 |   __pyx_type___pyx_array.tp_print = 0;
          |                         ^
    KDEpy/cutils.c:18649:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
    18649 |   __pyx_type___pyx_MemviewEnum.tp_print = 0;
          |                               ^
    KDEpy/cutils.c:18664:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
    18664 |   __pyx_type___pyx_memoryview.tp_print = 0;
          |                              ^
    KDEpy/cutils.c:18677:35: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
    18677 |   __pyx_type___pyx_memoryviewslice.tp_print = 0;
          |                                   ^
    KDEpy/cutils.c: In function ‘__Pyx_ParseOptionalKeywords’:
    KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19320:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
      580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
          |                                             ^~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19320:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
      580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
          |                                             ^~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                     ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
      580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
          |                                             ^~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
      580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
          |                                             ^~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c:19336:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
    19336 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
          |                         ^
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    KDEpy/cutils.c: In function ‘__Pyx_decode_c_string’:
    KDEpy/cutils.c:20396:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
    20396 |         return PyUnicode_FromUnicode(NULL, 0);
          |         ^~~~~~
    In file included from /usr/include/python3.9/unicodeobject.h:1026,
                     from /usr/include/python3.9/Python.h:97,
                     from KDEpy/cutils.c:4:
    /usr/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
      551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
          |                                          ^~~~~~~~~~~~~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w9uncvgw/kdepy_5ea3cd831da8443687772eb1fb15396c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rx_8z9nx/install-record.txt --single-version-externally-managed --compile --install-headers /home/mbr085/.virtualenvs/mergeforest-mvpxmIAj/include/site/python3.9/KDEpy Check the logs for full command output.

**Comment by tommyod** [comment]
Python 3.9 is not supported due to dependencies not supporting it fully. Use Python 3.8 instead.

**Comment by mbr085** [comment]
Rebuilding from cython solved the issue.

**Comment by tommyod** [comment]
Great! :+1:

**Comment by mbr085** [comment]
Now it installed, but it might not work... I will see what happens and report back if I have any issues.
