### ISSUE TITLE
Defining the limits of the grid

### ISSUE THREAD

**Issue by dbikiel** [tommyod/KDEpy#94]
Hi,

I am trying to perform several 2D estimations in the same grid (different groups in the same XY space). In order to compute the KDE I am passing the data for each group. However, given that the limits are not necessarily the same, I can't use the resulting KDE (I want to operate on the KDEs, but the grids are not the same...). Is there a way to fix the limits of the x and y scale? I saw that you can do it for 1D like np.linspace(-5, 5, 128), but when I try to do something similar in 2D it fails:

#Setting for x
grid, points = kde.fit(data).evaluate(np.linspace(-0.5, 20, 128))

#Gives
ValueError: Shape of data and grid points must be the same.

#Trying to set x and y
grid, points = kde.fit(data).evaluate((np.linspace(-0.5, 20, 128),np.linspace(-0.5, 20, 128)))

#Gives 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by dbikiel** [comment]
I think I found how to properly set the grid externally:

X, Y = np.mgrid[-0.5:20:128j, -0.5:20:128j]
grid_points = np.hstack([X.flatten().reshape(-1,1),Y.flatten().reshape(-1,1)])

kde = FFTKDE(kernel='gaussian', bw = 1)
points = kde.fit(data).evaluate(grid_points)

**Comment by tommyod** [comment]
You figured it out :)
