### ISSUE TITLE
Discrepancy in automated bandwidth selection?

### ISSUE THREAD

**Issue by lacerbi** [tommyod/KDEpy#95]
Hello,

I have been working on porting Botev et al. (2010) algorithm for KDE in 1D from MATLAB to Python (original code from the author's page [here](https://web.maths.unsw.edu.au/~zdravkobotev/)) since I was very unhappy with the `scipy` KDE.  To double-check, I also looked online for Python implementations of Botev et al., so I found your repo among others.

I just wanted to give you a heads-up about a potential discrepancy in your implementation.  In `bw_selection.py` -> `_fixed_point`, lines 63 and 79, you have `f = (0.5) * np.pi ...`. However, both in the MATLAB original and in the [implementation by Daniel B. Smith](https://github.com/Daniel-B-Smith/KDE-for-SciPy/blob/master/kde.py), that part is `f = (2.0) * np.pi ...`. Since I see that you commented your code fairly well but did not add a note here to explain the reason for the difference, I just wanted to point it out. As far as I can tell, you don't seem to have changed the multiplicative constant elsewhere to adjust for this.

When I run that snippet, your code seems to work differently from Botev et al. in that the bandwidth you return is substantially larger (by a factor of ~2) than the one returned by Botev's MATLAB implementation (on exactly the same data). However, I might be missing other changes you made in the code. Still, might be worth double-checking.

**Comment by tommyod** [comment]
Good catch. I believe the error is in the MATLAB code, not in KDEPy. 

See [this PR](https://github.com/tommyod/KDEpy/pull/51)  and [this issue](https://github.com/tommyod/KDEpy/issues/27) and let me know if you agree.

If you want to (and agree with the above), feel free to create a PR with a comment in the code linking to those PRs issues, or explaining with a sentence.

**Comment by lacerbi** [comment]
Thanks for the clarification. I wrote to Botev, hopefully we can get a definite answer directly  from the source.

Either way, it would be probably useful if you added a comment in the code, briefly explaining the discrepancy (e.g., specifying that you follow the textbook definition as opposed the MATLAB implementation - at the moment it's confusing because you only mention as reference the implementation by Daniel B. Smith, PhD, which is a direct implementation of the MATLAB code).

**Comment by lacerbi** [comment]
**The current implementation of bandwidth selection in `KDEpy` is wrong.**

Botev very kindly got back to me quickly and explained that _there is no discrepancy between the book and his original MATLAB implementation_.  The factor of 4 that seems missing in the `fixed_point` function comes from a different definition of `a2` in the main function. In the MATLAB code (as in your current Python implementation), `a2 = a(2:end).^2 / 4.0`. In the book, `a2 = a(2:end).^2`. So the definitions for him end up being equivalent in the `fixed_point` subroutine (in the book and in his original code).

However, the current `KDEpy` implementation mixes the two definitions.

This was easy to see by looking at the full algorithm in the book btw, which I should have done myself before contacting Botev (I had understood that you guys had looked at the algorithm in the book before making any change).

![image](https://user-images.githubusercontent.com/14820738/119216384-12728a80-badc-11eb-9b37-290b95150ab4.png)

**Comment by tommyod** [comment]
Thanks a lot for following up on this @lacerbi. To be sure I understand completely, if it's changed back to `2.0` it will be correct?

I'll look over the code and compare, then merge a PR once I understand it. 👍  I have to admit that while it might be easy to see, I was quite confused juggling MATLAB code, the paper, and snippets from Botevs book trying to get it right. More likely than not this is just me being slow though.

**Comment by tommyod** [comment]
Thanks a lot for following up on this @lacerbi. To be sure I understand completely, if it's changed back to 2.0 it will be correct?

**Comment by lacerbi** [comment]
No worries - the mismatch in definition can be quite misleading. I also was thrown off by the code snippet for `fixed_point`. This was a good reminder not to analyze code snippets in a vacuum, without double-checking the definitions...

Yes, the original version you had with `f = (2.0) * np.pi ...` (lines 63 and 79) was correct.
