### ISSUE TITLE
Using KDEpy in Global Mapper Pro v23

### ISSUE THREAD

**Issue by vkbellis** [tommyod/KDEpy#99]
Hello Tommy,
Global Mapper Pro v23 (currently in beta) will support running Python scripts through its own script editor and I wondered what you thought about possibly using KDEpy with point features loaded into a Global Mapper workspace? Ingestion of point features into KDEpy is one hurdle. The second hurdle would be the vector output from KDEpy; e.g., line and area features. 

I realize this may seem like an oddball question from out in left field, but while researching point density visualizations, the illustration of KDEpy's Fast 2D computations using binning and FFT looked exactly what I've been trying to accomplish graphically from raster heat maps.

Ideation
https://drive.google.com/file/d/11m_l8BE6IqbaV8EFCnL_JfLDKWzg06nX/view?usp=sharing

**Comment by tommyod** [comment]
> I wondered what you thought about possibly using KDEpy with point features loaded into a Global Mapper workspace?

I'm not exactly sure what you're asking. I have no thoughts in particular. I don't know anything about Global Mapper Pro. You're welcome to use KDEpy for whatever you want as long as it obeys the [license](https://github.com/tommyod/KDEpy/blob/master/LICENSE).

**Comment by vkbellis** [comment]
Thanks Tommy.
